import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c] ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 max-w-screen-md mx-auto">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            TODOS
          </h1>
          <input type="text" placeholder="What do you need to get done?" className="w-full p-4 text-lg font-semibold text-white bg-[#3c1a7f] rounded-lg shadow-md" />
          <hr></hr>
          <div className="container flex flex-col">
            {[1,2,3,4].map((_, i) => {
              return (
                <div className="flex items-center justify-between w-full p-4 mb-4 text-lg font-semibold text-white bg-[#3c1a7f] hover:bg-[#4A11B2] rounded-lg shadow-md cursor-pointer">
                    <div>
                      <input id={`todo ${i}`} type="checkbox" className="mr-4 w-4 h-4 rounded-xl bg-[#3c1a7f]  border cursor-pointer" />
                      <label htmlFor={`todo ${i}`}>TODO {i}</label>
                    </div>
                    <span className="text-2xl font-bold hover:text-red-500 ">X</span>
                </div>
              );
            })
            }
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
